STAR_WARS_MOVIES = {
    11: "Star Wars",
    1891: "The Empire Strikes Back",
    1892: "Return of the Jedi",
    1893: "Star Wars: Episode I - The Phantom Menace",
    1894: "Star Wars: Episode II - Attack of the Clones",
    1895: "Star Wars: Episode III - Revenge of the Sith",
    140607: "Star Wars: The Force Awakens",
    330459: "Rogue One: A Star Wars Story",
    181808: "Star Wars: The Last Jedi",
    348350: "Solo: A Star Wars Story",
    181812: "Star Wars: The Rise of Skywalker",
    1228710: "The Mandalorian and Grogu",
    1417668: "Star Wars: Starfighter",
}

STAR_WARS_TV = {
    3122: "Star Wars: Clone Wars",
    4194: "Star Wars: The Clone Wars",
    60554: "Star Wars Rebels",
    82856: "The Mandalorian",
    105971: "Star Wars: The Bad Batch",
    114478: "Star Wars: Visions",
    115036: "The Book of Boba Fett",
    92830: "Obi-Wan Kenobi",
    83867: "Andor",
    203085: "Star Wars: Tales of the Jedi",
    202998: "Star Wars: Young Jedi Adventures",
    114461: "Ahsoka",
    251091: "Star Wars: Tales of the Empire",
    114479: "The Acolyte",
    202879: "Star Wars: Skeleton Crew",
    288055: "Star Wars: Tales of the Underworld",
    289219: "Star Wars: Maul - Shadow Lord",
}

STAR_WARS_EXTRAS = {
    # Pre-Disney era TV movies / cartoons — canon-adjacent, ambiguous
    1884: {"title": "The Ewok Adventure", "type": "movie"},
    10372: {"title": "Ewoks: The Battle for Endor", "type": "movie"},
    25: {"title": "Star Wars: Droids", "type": "tv"},
    3478: {"title": "Ewoks", "type": "tv"},

    # LEGO Star Wars specials/shows
    63722: {"title": "LEGO Star Wars: Droid Tales", "type": "tv"},
    66487: {"title": "LEGO Star Wars: The Resistance Rises", "type": "tv"},
    66837: {"title": "LEGO Star Wars: The Freemaker Adventures", "type": "tv"},
    70608: {"title": "LEGO Star Wars: The Padawan Menace", "type": "movie"},
    79158: {"title": "LEGO Star Wars: Bombad Bounty", "type": "movie"},
    81234: {"title": "LEGO Star Wars: Revenge of The Brick", "type": "movie"},
    136406: {"title": "LEGO Star Wars: The Empire Strikes Out", "type": "movie"},
    139282: {"title": "Lego Indiana Jones and the Raiders of the Lost Brick", "type": "movie"},
    732670: {"title": "LEGO Star Wars Holiday Special", "type": "movie"},
    857702: {"title": "LEGO Star Wars Terrifying Tales", "type": "movie"},
    980804: {"title": "LEGO Star Wars Summer Vacation", "type": "movie"},
    83558: {"title": "LEGO Star Wars: All-Stars", "type": "tv"},
    253760: {"title": "LEGO Star Wars: Rebuild the Galaxy", "type": "tv"},
    289411: {"title": "LEGO Star Wars: Rebuild the Galaxy - Pieces of the Past", "type": "tv"},
    1731694: {"title": "LEGO Star Wars: The Mandalorian", "type": "movie"},

    # Documentaries / making-of
    72694: {"title": "The Making of Star Wars", "type": "movie"},
    72803: {"title": "SP FX: The Empire Strikes Back", "type": "movie"},
    35795: {"title": "From Star Wars to Jedi: The Making of a Saga", "type": "movie"},
    65083: {"title": "The Beginning: The Making of Star Wars Episode I", "type": "movie"},
    47025: {"title": "R2-D2: Beneath the Dome", "type": "movie"},
    435147: {"title": "From Puppets to Pixels: The Making of Star Wars Episode II", "type": "movie"},
    435365: {"title": "The Story of Star Wars", "type": "movie"},
    1547936: {"title": "The Force Is with Them: The Legacy of 'Star Wars'", "type": "movie"},
    76180: {"title": "Empire of Dreams: The Story of the Star Wars Trilogy", "type": "movie"},
    489246: {"title": "Clone Wars: Bridging the Saga", "type": "movie"},
    432134: {"title": "Star Wars: Heroes & Villains", "type": "movie"},
    72448: {"title": "Star Wars: A Musical Journey", "type": "movie"},
    72513: {"title": "Within a Minute: The Making of Star Wars Episode III", "type": "movie"},
    128295: {"title": "Star Wars: The Legacy Revealed", "type": "movie"},
    388885: {"title": "Secrets of the Force Awakens: A Cinematic Journey", "type": "movie"},
    507052: {"title": "The Force of Sound", "type": "movie"},
    513696: {"title": "Balance of the Force", "type": "movie"},
    510714: {"title": "The Director and the Jedi", "type": "movie"},
    680382: {"title": "The Skywalker Legacy", "type": "movie"},
    201285: {"title": "LIGHT & MAGIC", "type": "tv"},
    877181: {"title": "Under the Helmet: The Legacy of Boba Fett", "type": "movie"},
    1076708: {"title": "Music by John Williams", "type": "movie"},
    1076366: {"title": "Willow: Behind the Magic", "type": "movie"},

    # Robot Chicken parody specials
    42979: {"title": "Robot Chicken: Star Wars", "type": "movie"},
    42982: {"title": "Robot Chicken: Star Wars Episode II", "type": "movie"},
    51888: {"title": "Robot Chicken: Star Wars Episode III", "type": "movie"},
}